// GENERATED by scripts/build-seed.py from the Oson Ish export — edit the overrides, not this file.
// Source: https://osonish.uz/vacancies?region=1712&city=1712216 (soato_district=1712216), fetched 2026-09-08.

import type { Mahalla } from "@/types";

export const mahallas: Mahalla[] = [
  {
    "id": "alisher-navoiy",
    "name": {
      "uz": "Alisher Navoiy",
      "ru": "Алишер Навоий"
    },
    "nameCyrl": "Алишер Навоий маҳалласи",
    "sourceId": 3023
  },
  {
    "id": "arabxona",
    "name": {
      "uz": "Arabxona",
      "ru": "Арабхона"
    },
    "nameCyrl": "Арабхона маҳалласи",
    "sourceId": 3024
  },
  {
    "id": "ayronchi",
    "name": {
      "uz": "Ayronchi",
      "ru": "Айрончи"
    },
    "nameCyrl": "Айрончи маҳалласи",
    "sourceId": 3034
  },
  {
    "id": "azizobod",
    "name": {
      "uz": "Azizobod",
      "ru": "Азизобод"
    },
    "nameCyrl": "Азизобод маҳалласи",
    "sourceId": 3022
  },
  {
    "id": "bashir",
    "name": {
      "uz": "Bashir",
      "ru": "Башир"
    },
    "nameCyrl": "Башир маҳалласи",
    "sourceId": 3011
  },
  {
    "id": "bobodogi",
    "name": {
      "uz": "Bobodoʻgʻi",
      "ru": "Бободўғи"
    },
    "nameCyrl": "Бободўғи маҳалласи",
    "sourceId": 2997
  },
  {
    "id": "bolakrabot",
    "name": {
      "uz": "Boʻlakrabot",
      "ru": "Бўлакработ"
    },
    "nameCyrl": "Бўлакработ маҳалласи",
    "sourceId": 3035
  },
  {
    "id": "boston",
    "name": {
      "uz": "Boʻston",
      "ru": "Бўстон"
    },
    "nameCyrl": "Бўстон маҳалласи",
    "sourceId": 3036
  },
  {
    "id": "demas",
    "name": {
      "uz": "Demas",
      "ru": "Демас"
    },
    "nameCyrl": "Демас маҳалласи",
    "sourceId": 3027
  },
  {
    "id": "furqat",
    "name": {
      "uz": "Furqat",
      "ru": "Фурқат"
    },
    "nameCyrl": "Фурқат маҳалласи",
    "sourceId": 3006
  },
  {
    "id": "gulbog",
    "name": {
      "uz": "Gulbogʻ",
      "ru": "Гулбоғ"
    },
    "nameCyrl": "Гулбоғ маҳалласи",
    "sourceId": 3026
  },
  {
    "id": "gulzor",
    "name": {
      "uz": "Gulzor",
      "ru": "Гулзор"
    },
    "nameCyrl": "Гулзор маҳалласи",
    "sourceId": 2999
  },
  {
    "id": "gumbaz",
    "name": {
      "uz": "Gumbaz",
      "ru": "Гумбаз"
    },
    "nameCyrl": "Гумбаз маҳалласи",
    "sourceId": 3038
  },
  {
    "id": "gamxor",
    "name": {
      "uz": "Gʻamxoʻr",
      "ru": "Ғамхўр"
    },
    "nameCyrl": "Ғамхўр маҳалласи",
    "sourceId": 2998
  },
  {
    "id": "goyibon",
    "name": {
      "uz": "Gʻoyibon",
      "ru": "Ғойибон"
    },
    "nameCyrl": "Ғойибон маҳалласи",
    "sourceId": 3037
  },
  {
    "id": "konsurun",
    "name": {
      "uz": "Konsurun",
      "ru": "Консурун"
    },
    "nameCyrl": "Консурун маҳалласи",
    "sourceId": 3029
  },
  {
    "id": "kulolon",
    "name": {
      "uz": "Kulolon",
      "ru": "Кулолон"
    },
    "nameCyrl": "Кулолон маҳалласи",
    "sourceId": 3013
  },
  {
    "id": "kusharta",
    "name": {
      "uz": "Kusharta",
      "ru": "Кушарта"
    },
    "nameCyrl": "Кушарта маҳалласи",
    "sourceId": 3014
  },
  {
    "id": "madaniyat",
    "name": {
      "uz": "Madaniyat",
      "ru": "Маданият"
    },
    "nameCyrl": "Маданият маҳалласи",
    "sourceId": 3015
  },
  {
    "id": "malikobod",
    "name": {
      "uz": "Malikobod",
      "ru": "Маликобод"
    },
    "nameCyrl": "Маликобод маҳалласи",
    "sourceId": 3001
  },
  {
    "id": "mustaqillik",
    "name": {
      "uz": "Mustaqillik",
      "ru": "Мустақиллик"
    },
    "nameCyrl": "Мустақиллик",
    "sourceId": 11389
  },
  {
    "id": "nurafshon",
    "name": {
      "uz": "Nurafshon",
      "ru": "Нурафшон"
    },
    "nameCyrl": "Нурафшон",
    "sourceId": 11384
  },
  {
    "id": "oboddiyor",
    "name": {
      "uz": "Oboddiyor",
      "ru": "Ободдиёр"
    },
    "nameCyrl": "Ободдиёр",
    "sourceId": 11387
  },
  {
    "id": "okmachit",
    "name": {
      "uz": "Okmachit",
      "ru": "Окмачит"
    },
    "nameCyrl": "Окмачит маҳалласи",
    "sourceId": 3017
  },
  {
    "id": "okrabot",
    "name": {
      "uz": "Okrabot",
      "ru": "Окработ"
    },
    "nameCyrl": "Окработ маҳалласи",
    "sourceId": 3002
  },
  {
    "id": "oksoch",
    "name": {
      "uz": "Oksoch",
      "ru": "Оксоч"
    },
    "nameCyrl": "Оксоч маҳалласи",
    "sourceId": 3041
  },
  {
    "id": "ortaqorgon",
    "name": {
      "uz": "Oʻrtaqoʻrgʻon",
      "ru": "Ўртақўрғон"
    },
    "nameCyrl": "Ўртақўрғон маҳалласи",
    "sourceId": 3005
  },
  {
    "id": "ozbekiston",
    "name": {
      "uz": "Oʻzbekiston",
      "ru": "Ўзбекистон"
    },
    "nameCyrl": "Ўзбекистон маҳалласи",
    "sourceId": 3031
  },
  {
    "id": "paxtaobod",
    "name": {
      "uz": "Paxtaobod",
      "ru": "Пахтаобод"
    },
    "nameCyrl": "Пахтаобод маҳалласи",
    "sourceId": 3018
  },
  {
    "id": "qalayi-azizon",
    "name": {
      "uz": "Qalʻʻayi-Azizon",
      "ru": "Қалъайи-Азизон"
    },
    "nameCyrl": "Қалъайи-Азизон маҳалласи",
    "sourceId": 3000
  },
  {
    "id": "saroy",
    "name": {
      "uz": "Saroy",
      "ru": "Сарой"
    },
    "nameCyrl": "Сарой",
    "sourceId": 3003
  },
  {
    "id": "sheyxon",
    "name": {
      "uz": "Sheyxon",
      "ru": "Шейхон"
    },
    "nameCyrl": "Шейхон маҳалласи",
    "sourceId": 3033
  },
  {
    "id": "sufiyon",
    "name": {
      "uz": "Sufiyon",
      "ru": "Суфиён"
    },
    "nameCyrl": "Суфиён маҳалласи",
    "sourceId": 3042
  },
  {
    "id": "tavois",
    "name": {
      "uz": "Tavois",
      "ru": "Тавоис"
    },
    "nameCyrl": "Тавоис маҳалласи",
    "sourceId": 3043
  },
  {
    "id": "tojikon",
    "name": {
      "uz": "Tojikon",
      "ru": "Тожикон"
    },
    "nameCyrl": "Тожикон маҳалласи",
    "sourceId": 3019
  },
  {
    "id": "toshmachit",
    "name": {
      "uz": "Toshmachit",
      "ru": "Тошмачит"
    },
    "nameCyrl": "Тошмачит маҳалласи",
    "sourceId": 3020
  },
  {
    "id": "uzilishkent",
    "name": {
      "uz": "Uzilishkent",
      "ru": "Узилишкент"
    },
    "nameCyrl": "Узилишкент маҳалласи",
    "sourceId": 3004
  },
  {
    "id": "vangozi",
    "name": {
      "uz": "Vangʻozi",
      "ru": "Ванғози"
    },
    "nameCyrl": "Ванғози маҳалласи",
    "sourceId": 3012
  },
  {
    "id": "varozun",
    "name": {
      "uz": "Varozun",
      "ru": "Варозун"
    },
    "nameCyrl": "Варозун",
    "sourceId": 3025
  },
  {
    "id": "xafkoriyon",
    "name": {
      "uz": "Xafkoriyon",
      "ru": "Хафкориён"
    },
    "nameCyrl": "Хафкориён маҳалласи",
    "sourceId": 3021
  },
  {
    "id": "xomrabot",
    "name": {
      "uz": "Xomrabot",
      "ru": "Хомработ"
    },
    "nameCyrl": "Хомработ маҳалласи",
    "sourceId": 3044
  },
  {
    "id": "xojaqorgon",
    "name": {
      "uz": "Xoʻjaqoʻrgʻon",
      "ru": "Хўжақўрғон"
    },
    "nameCyrl": "Хўжақўрғон маҳалласи",
    "sourceId": 3007
  },
  {
    "id": "xumo",
    "name": {
      "uz": "Xumo",
      "ru": "Хумо"
    },
    "nameCyrl": "Хумо",
    "sourceId": 11383
  },
  {
    "id": "xusbuddin",
    "name": {
      "uz": "Xusbuddin",
      "ru": "Хусбуддин"
    },
    "nameCyrl": "Хусбуддин маҳалласи",
    "sourceId": 3032
  },
  {
    "id": "yangi-hayot-qfy",
    "name": {
      "uz": "Yangi-hayot QFY",
      "ru": "Янги-ҳаёт ҚФЙ"
    },
    "nameCyrl": "Янги-ҳаёт ҚФЙ",
    "sourceId": 3009
  },
  {
    "id": "yashnaobod",
    "name": {
      "uz": "Yashnaobod",
      "ru": "Яшнаобод"
    },
    "nameCyrl": "Яшнаобод",
    "sourceId": 11392
  },
  {
    "id": "zarmetan",
    "name": {
      "uz": "Zarmetan",
      "ru": "Зарметан"
    },
    "nameCyrl": "Зарметан маҳалласи",
    "sourceId": 3028
  },
  {
    "id": "ziyokor",
    "name": {
      "uz": "Ziyokor",
      "ru": "Зиёкор"
    },
    "nameCyrl": "Зиёкор",
    "sourceId": 11386
  }
];
