// GENERATED by scripts/build-seed.py from the Oson Ish export — edit the overrides, not this file.
// Source: https://osonish.uz/vacancies?region=1712&city=1712216 (soato_district=1712216), fetched 2026-09-08.

import type { Mahalla } from "@/types";

export const mahallas: Mahalla[] = [
  {
    "id": "alisher-navoiy",
    "name": {
      "uz": "Alisher Navoiy",
      "ru": "Алишер Навоий"
    },
    "nameCyrl": "Алишер Навоий МФЙ",
    "sourceId": 3023
  },
  {
    "id": "arabxona",
    "name": {
      "uz": "Arabxona",
      "ru": "Арабхона"
    },
    "nameCyrl": "Арабхона МФЙ",
    "sourceId": 3024
  },
  {
    "id": "ayronchi",
    "name": {
      "uz": "Ayronchi",
      "ru": "Айрончи"
    },
    "nameCyrl": "Айрончи МФЙ",
    "sourceId": 3034
  },
  {
    "id": "azizobod",
    "name": {
      "uz": "Azizobod",
      "ru": "Азизобод"
    },
    "nameCyrl": "Азизобод МФЙ",
    "sourceId": 3022
  },
  {
    "id": "bashir",
    "name": {
      "uz": "Bashir",
      "ru": "Башир"
    },
    "nameCyrl": "Башир МФЙ",
    "sourceId": 3011
  },
  {
    "id": "bobodogi",
    "name": {
      "uz": "Bobodoʻgʻi",
      "ru": "Бободўғи"
    },
    "nameCyrl": "Бободўғи МФЙ",
    "sourceId": 2997
  },
  {
    "id": "bolakrabot",
    "name": {
      "uz": "Boʻlakrabot",
      "ru": "Бўлакработ"
    },
    "nameCyrl": "Бўлакработ МФЙ",
    "sourceId": 3035
  },
  {
    "id": "boston",
    "name": {
      "uz": "Boʻston",
      "ru": "Бўстон"
    },
    "nameCyrl": "Бўстон МФЙ",
    "sourceId": 3036
  },
  {
    "id": "demas",
    "name": {
      "uz": "Demas",
      "ru": "Демас"
    },
    "nameCyrl": "Демас МФЙ",
    "sourceId": 3027
  },
  {
    "id": "furqat",
    "name": {
      "uz": "Furqat",
      "ru": "Фурқат"
    },
    "nameCyrl": "Фурқат МФЙ",
    "sourceId": 3006
  },
  {
    "id": "gulbog",
    "name": {
      "uz": "Gulbogʻ",
      "ru": "Гулбоғ"
    },
    "nameCyrl": "Гулбоғ МФЙ",
    "sourceId": 3026
  },
  {
    "id": "gulzor",
    "name": {
      "uz": "Gulzor",
      "ru": "Гулзор"
    },
    "nameCyrl": "Гулзор МФЙ",
    "sourceId": 2999
  },
  {
    "id": "gumbaz",
    "name": {
      "uz": "Gumbaz",
      "ru": "Гумбаз"
    },
    "nameCyrl": "Гумбаз МФЙ",
    "sourceId": 3038
  },
  {
    "id": "gamxor",
    "name": {
      "uz": "Gʻamxoʻr",
      "ru": "Ғамхўр"
    },
    "nameCyrl": "Ғамхўр МФЙ",
    "sourceId": 2998
  },
  {
    "id": "goyibon",
    "name": {
      "uz": "Gʻoyibon",
      "ru": "Ғойибон"
    },
    "nameCyrl": "Ғойибон МФЙ",
    "sourceId": 3037
  },
  {
    "id": "konsurun",
    "name": {
      "uz": "Konsurun",
      "ru": "Консурун"
    },
    "nameCyrl": "Консурун МФЙ",
    "sourceId": 3029
  },
  {
    "id": "kulolon",
    "name": {
      "uz": "Kulolon",
      "ru": "Кулолон"
    },
    "nameCyrl": "Кулолон МФЙ",
    "sourceId": 3013
  },
  {
    "id": "kusharti",
    "name": {
      "uz": "Kusharti",
      "ru": "Кушарти"
    },
    "nameCyrl": "Кушарти МФЙ",
    "sourceId": 3014
  },
  {
    "id": "madaniyat",
    "name": {
      "uz": "Madaniyat",
      "ru": "Маданият"
    },
    "nameCyrl": "Маданият МФЙ",
    "sourceId": 3015
  },
  {
    "id": "malikobod",
    "name": {
      "uz": "Malikobod",
      "ru": "Маликобод"
    },
    "nameCyrl": "Маликобод МФЙ",
    "sourceId": 3001
  },
  {
    "id": "mustaqillik",
    "name": {
      "uz": "Mustaqillik",
      "ru": "Мустақиллик"
    },
    "nameCyrl": "Мустақиллик МФЙ",
    "sourceId": 11389
  },
  {
    "id": "nurafshon",
    "name": {
      "uz": "Nurafshon",
      "ru": "Нурафшон"
    },
    "nameCyrl": "Нурафшон МФЙ",
    "sourceId": 11384
  },
  {
    "id": "obod-diyor",
    "name": {
      "uz": "Obod diyor",
      "ru": "Обод диёр"
    },
    "nameCyrl": "Обод диёр МФЙ",
    "sourceId": 11387
  },
  {
    "id": "oq-machit",
    "name": {
      "uz": "Oq machit",
      "ru": "Оқ мачит"
    },
    "nameCyrl": "Оқ мачит МФЙ",
    "sourceId": 3017
  },
  {
    "id": "oqrabot",
    "name": {
      "uz": "Oqrabot",
      "ru": "Оқработ"
    },
    "nameCyrl": "Оқработ МФЙ",
    "sourceId": 3002
  },
  {
    "id": "oqsoch",
    "name": {
      "uz": "Oqsoch",
      "ru": "Оқсоч"
    },
    "nameCyrl": "Оқсоч МФЙ",
    "sourceId": 3041
  },
  {
    "id": "ortaqorgon",
    "name": {
      "uz": "Oʻrtaqoʻrgʻon",
      "ru": "Ўртақўрғон"
    },
    "nameCyrl": "Ўртақўрғон МФЙ",
    "sourceId": 3005
  },
  {
    "id": "ozbekiston",
    "name": {
      "uz": "Oʻzbekiston",
      "ru": "Ўзбекистон"
    },
    "nameCyrl": "Ўзбекистон МФЙ",
    "sourceId": 3031
  },
  {
    "id": "paxtaobod",
    "name": {
      "uz": "Paxtaobod",
      "ru": "Пахтаобод"
    },
    "nameCyrl": "Пахтаобод МФЙ",
    "sourceId": 3018
  },
  {
    "id": "qalayi-azizon",
    "name": {
      "uz": "Qalʼayi Azizon",
      "ru": "Қалъайи Азизон"
    },
    "nameCyrl": "Қалъайи Азизон МФЙ",
    "sourceId": 3000
  },
  {
    "id": "saroy",
    "name": {
      "uz": "Saroy",
      "ru": "Сарой"
    },
    "nameCyrl": "Сарой МФЙ",
    "sourceId": 3003
  },
  {
    "id": "shayxon",
    "name": {
      "uz": "Shayxon",
      "ru": "Шайхон"
    },
    "nameCyrl": "Шайхон МФЙ",
    "sourceId": 3033
  },
  {
    "id": "sofiyon",
    "name": {
      "uz": "Soʻfiyon",
      "ru": "Сўфиён"
    },
    "nameCyrl": "Сўфиён МФЙ",
    "sourceId": 3042
  },
  {
    "id": "tavois",
    "name": {
      "uz": "Tavois",
      "ru": "Тавоис"
    },
    "nameCyrl": "Тавоис МФЙ",
    "sourceId": 3043
  },
  {
    "id": "tojikon",
    "name": {
      "uz": "Tojikon",
      "ru": "Тожикон"
    },
    "nameCyrl": "Тожикон МФЙ",
    "sourceId": 3019
  },
  {
    "id": "toshmachit",
    "name": {
      "uz": "Toshmachit",
      "ru": "Тошмачит"
    },
    "nameCyrl": "Тошмачит МФЙ",
    "sourceId": 3020
  },
  {
    "id": "uzilishkent",
    "name": {
      "uz": "Uzilishkent",
      "ru": "Узилишкент"
    },
    "nameCyrl": "Узилишкент МФЙ",
    "sourceId": 3004
  },
  {
    "id": "vangozi",
    "name": {
      "uz": "Vangʻozi",
      "ru": "Ванғози"
    },
    "nameCyrl": "Ванғози МФЙ",
    "sourceId": 3012
  },
  {
    "id": "varozun",
    "name": {
      "uz": "Varozun",
      "ru": "Варозун"
    },
    "nameCyrl": "Варозун МФЙ",
    "sourceId": 3025
  },
  {
    "id": "xafkoriyon",
    "name": {
      "uz": "Xafkoriyon",
      "ru": "Хафкориён"
    },
    "nameCyrl": "Хафкориён МФЙ",
    "sourceId": 3021
  },
  {
    "id": "xomrabot",
    "name": {
      "uz": "Xomrabot",
      "ru": "Хомработ"
    },
    "nameCyrl": "Хомработ МФЙ",
    "sourceId": 3044
  },
  {
    "id": "xojaqorgon",
    "name": {
      "uz": "Xoʻjaqoʻrgʻon",
      "ru": "Хўжақўрғон"
    },
    "nameCyrl": "Хўжақўрғон МФЙ",
    "sourceId": 3007
  },
  {
    "id": "xumo",
    "name": {
      "uz": "Xumo",
      "ru": "Хумо"
    },
    "nameCyrl": "Хумо МФЙ",
    "sourceId": 11383
  },
  {
    "id": "xusbuddin",
    "name": {
      "uz": "Xusbuddin",
      "ru": "Хусбуддин"
    },
    "nameCyrl": "Хусбуддин МФЙ",
    "sourceId": 3032
  },
  {
    "id": "yangi-hayot",
    "name": {
      "uz": "Yangi hayot",
      "ru": "Янги ҳаёт"
    },
    "nameCyrl": "Янги ҳаёт МФЙ",
    "sourceId": 3009
  },
  {
    "id": "yashnaobod",
    "name": {
      "uz": "Yashnaobod",
      "ru": "Яшнаобод"
    },
    "nameCyrl": "Яшнаобод МФЙ",
    "sourceId": 11392
  },
  {
    "id": "zarmetan",
    "name": {
      "uz": "Zarmetan",
      "ru": "Зарметан"
    },
    "nameCyrl": "Зарметан МФЙ",
    "sourceId": 3028
  },
  {
    "id": "ziyokor",
    "name": {
      "uz": "Ziyokor",
      "ru": "Зиёкор"
    },
    "nameCyrl": "Зиёкор МФЙ",
    "sourceId": 11386
  }
];
