// GENERATED by scripts/build-seed.py from the Oson Ish export — edit the overrides, not this file.
// Source: https://osonish.uz/vacancies?region=1712&city=1712216 (soato_district=1712216), fetched 2026-09-08.

import type { Organization } from "@/types";

export const organizations: Organization[] = [
  {
    "id": "org-33883",
    "slug": "22-son-shodlik-madaniyat-markazi",
    "name": {
      "uz": "22-son \"Shodlik\" madaniyat markazi",
      "ru": "Центр культуры № 22 «Шодлик»"
    },
    "legalName": "\"22-SON SHODLIK MADANIYAT MARKAZI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "312342636",
    "sectorId": "xizmatlar",
    "mahallaId": "okmachit",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Окмачит",
    "description": null,
    "isMajor": false,
    "sourceId": 33883
  },
  {
    "id": "org-6475",
    "slug": "4-sonli-ayrim-fanlar-chuqur-oqitiladigan-sinflari-mavjud-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "4-sonli ayrim fanlar chuqur oʻqitiladigan sinflari mavjud umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 4 с классами углублённого изучения отдельных предметов"
    },
    "legalName": "\"4-SONLI AYRIM FANLAR CHUQUR O‘QITILADIGAN SINFLARI MAVJUD UMUMIY O‘RTA TA’LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "203180940",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Qiziltepa tuman 4-maktab",
    "description": null,
    "isMajor": false,
    "sourceId": 6475
  },
  {
    "id": "org-931",
    "slug": "5-sonli-ayrim-fanlar-chuqur-oqitiladigan-sinflari-mavjud-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "5-sonli ayrim fanlar chuqur oʻqitiladigan sinflari mavjud umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 5 с классами углублённого изучения отдельных предметов"
    },
    "legalName": "\"5-SONLI AYRIM FANLAR CHUQUR O‘QITILADIGAN SINFLARI MAVJUD UMUMIY O‘RTA TA’LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "203161164",
    "sectorId": "talim",
    "mahallaId": "ozbekiston",
    "address": "Qiziltepa tuman Oʻzbekiston mfy",
    "description": null,
    "isMajor": true,
    "sourceId": 931
  },
  {
    "id": "org-35856",
    "slug": "afirash",
    "name": {
      "uz": "Afirash",
      "ru": "ООО «Afirash»"
    },
    "legalName": "\"AFIRASH\" MAS`ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "308669688",
    "sectorId": "sanoat",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": false,
    "sourceId": 35856
  },
  {
    "id": "org-1109",
    "slug": "amu-buxoro-mashina-kanali-qiziltepa-tuman-boshqarmasi",
    "name": {
      "uz": "Amu-Buxoro mashina kanali Qiziltepa tuman boshqarmasi",
      "ru": "Кызылтепинское районное управление машинного канала Аму-Бухара"
    },
    "legalName": "\"AMU-BUXORO MASHINA KANALI QIZILTEPA TUMAN BOSHQARMASI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "200017218",
    "sectorId": "qurilish",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепа, проспект Узбекистан",
    "description": null,
    "isMajor": false,
    "sourceId": 1109
  },
  {
    "id": "org-34809",
    "slug": "binokor",
    "name": {
      "uz": "Binokor",
      "ru": "ООО «Binokor»"
    },
    "legalName": "\"BINOKOR \" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "203082026",
    "sectorId": "qurilish",
    "mahallaId": null,
    "address": "qiziltepa",
    "description": null,
    "isMajor": true,
    "sourceId": 34809
  },
  {
    "id": "org-36242",
    "slug": "firdavs-kapital-qurilish",
    "name": {
      "uz": "Firdavs Kapital Qurilish",
      "ru": "ООО «Firdavs Kapital Qurilish»"
    },
    "legalName": "\"FIRDAVS KAPITAL QURILISH\" MAS`ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "303723695",
    "sectorId": "qurilish",
    "mahallaId": "tavois",
    "address": "Навоийская область, Кызылтепинский район, махаллинский сход граждан Тавоис",
    "description": null,
    "isMajor": false,
    "sourceId": 36242
  },
  {
    "id": "org-13361",
    "slug": "navoiy-viloyati-sport-boshqarmasi-qiziltepa-tuman-sport-maktabi",
    "name": {
      "uz": "Navoiy viloyati sport boshqarmasi Qiziltepa tuman sport maktabi",
      "ru": "Спортивная школа Кызылтепинского района управления спорта Навоийской области"
    },
    "legalName": "\"NAVOIY VILOYATI SPORT BOSHQARMASI QIZILTEPA TUMAN SPORT MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "206908741",
    "sectorId": "sogliqni-saqlash",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район",
    "description": null,
    "isMajor": false,
    "sourceId": 13361
  },
  {
    "id": "org-14284",
    "slug": "ozyolkoprik-klasterining-navoiy-filiali",
    "name": {
      "uz": "Oʻzyoʻlkoʻprik klasterining Navoiy filiali",
      "ru": "Навоийский филиал кластера «Узйулкуприк»"
    },
    "legalName": "\"O'ZYO'LKO'PRIK KLASTERINING NAVOIY FILIALI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "203229093",
    "sectorId": "qurilish",
    "mahallaId": "goyibon",
    "address": "Навоийская область, Кызылтепинский район, махаллинский сход граждан Гойибон",
    "description": null,
    "isMajor": false,
    "sourceId": 14284
  },
  {
    "id": "org-15457",
    "slug": "qiziltepa-tuman-tibbiyot-birlashmasi",
    "name": {
      "uz": "Qiziltepa tuman tibbiyot birlashmasi",
      "ru": "Кызылтепинское районное медицинское объединение"
    },
    "legalName": "\"QIZILTEPA TUMAN TIBBIYOT BIRLASHMASI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "200017114",
    "sectorId": "xizmatlar",
    "mahallaId": "boston",
    "address": "Навоийская область, Кызылтепа, микрорайон Бустон",
    "description": null,
    "isMajor": false,
    "sourceId": 15457
  },
  {
    "id": "org-17214",
    "slug": "qiziltepa-tumani-1-sonli-oltin-baliqcha-mtt",
    "name": {
      "uz": "Qiziltepa tumani 1-sonli \"Oltin baliqcha\" MTT",
      "ru": "Детский сад № 1 «Олтин баликча» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  1-SONLI  OLTIN  BALIQCHA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207030238",
    "sectorId": "talim",
    "mahallaId": "alisher-navoiy",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Алишер Навои",
    "description": null,
    "isMajor": false,
    "sourceId": 17214
  },
  {
    "id": "org-11279",
    "slug": "qiziltepa-tumani-1-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 1-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 1 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 1-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206895095",
    "sectorId": "talim",
    "mahallaId": "boston",
    "address": "Boʻston mfy Mirzo Ulugʻbek koʻchasi 56-uy",
    "description": null,
    "isMajor": true,
    "sourceId": 11279
  },
  {
    "id": "org-12287",
    "slug": "qiziltepa-tumani-10-sonli-orom-mtt",
    "name": {
      "uz": "Qiziltepa tumani 10-sonli \"Orom\" MTT",
      "ru": "Детский сад № 10 «Ором» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  10-SONLI  OROM\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086294",
    "sectorId": "talim",
    "mahallaId": "oboddiyor",
    "address": "Navoiy viloyati Qiziltepa tumani OboddiyorMFY",
    "description": null,
    "isMajor": false,
    "sourceId": 12287
  },
  {
    "id": "org-4187",
    "slug": "qiziltepa-tumani-11-sonli-qaldirgoch-mtt",
    "name": {
      "uz": "Qiziltepa tumani 11-sonli \"Qaldirgʻoch\" MTT",
      "ru": "Детский сад № 11 «Калдиргоч» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 11-SONLI QALDIRG`OCH\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086254",
    "sectorId": "talim",
    "mahallaId": "oksoch",
    "address": "Navoiy viloyati qiziltepa tumani Oqsoch MFY",
    "description": null,
    "isMajor": false,
    "sourceId": 4187
  },
  {
    "id": "org-6469",
    "slug": "qiziltepa-tumani-11-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 11-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 11 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 11-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206895064",
    "sectorId": "talim",
    "mahallaId": "madaniyat",
    "address": "Qiziltepa tuman Madaniyat MFY",
    "description": null,
    "isMajor": false,
    "sourceId": 6469
  },
  {
    "id": "org-33412",
    "slug": "qiziltepa-tumani-12-sonli-guldasta-mtt",
    "name": {
      "uz": "Qiziltepa tumani 12-sonli \"Guldasta\" MTT",
      "ru": "Детский сад № 12 «Гулдаста» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 12-SONLI GULDASTA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086247",
    "sectorId": "talim",
    "mahallaId": "oksoch",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Оксоч",
    "description": null,
    "isMajor": false,
    "sourceId": 33412
  },
  {
    "id": "org-6106",
    "slug": "qiziltepa-tumani-13-sonli-saodat-mtt",
    "name": {
      "uz": "Qiziltepa tumani 13-sonli \"Saodat\" MTT",
      "ru": "Детский сад № 13 «Саодат» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 13-SONLI SAODAT\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086223",
    "sectorId": "talim",
    "mahallaId": "okmachit",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Окмачит",
    "description": null,
    "isMajor": false,
    "sourceId": 6106
  },
  {
    "id": "org-10801",
    "slug": "qiziltepa-tumani-14-sonli-guncha-mtt",
    "name": {
      "uz": "Qiziltepa tumani 14-sonli \"Gʻuncha\" MTT",
      "ru": "Детский сад № 14 «Гунча» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 14-SONLI G`UNCHA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207030221",
    "sectorId": "talim",
    "mahallaId": "vangozi",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Вангози",
    "description": null,
    "isMajor": false,
    "sourceId": 10801
  },
  {
    "id": "org-3962",
    "slug": "qiziltepa-tumani-17-sonli-lola-mtt",
    "name": {
      "uz": "Qiziltepa tumani 17-sonli \"Lola\" MTT",
      "ru": "Детский сад № 17 «Лола» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 17-SONLI LOLA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "305522858",
    "sectorId": "talim",
    "mahallaId": "tavois",
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Тавоис",
    "description": null,
    "isMajor": false,
    "sourceId": 3962
  },
  {
    "id": "org-12389",
    "slug": "qiziltepa-tumani-17-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 17-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 17 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 17-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "205006891",
    "sectorId": "talim",
    "mahallaId": "sheyxon",
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Шейхан",
    "description": null,
    "isMajor": true,
    "sourceId": 12389
  },
  {
    "id": "org-33393",
    "slug": "qiziltepa-tumani-18-sonli-yulduzcha-mtt",
    "name": {
      "uz": "Qiziltepa tumani 18-sonli \"Yulduzcha\" MTT",
      "ru": "Детский сад № 18 «Юлдузча» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 18-SONLI YULDUZCHA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "305523104",
    "sectorId": "xizmatlar",
    "mahallaId": null,
    "address": "Навоийская область, Навбахорский район, махаллинский сход граждан Дулдул",
    "description": null,
    "isMajor": false,
    "sourceId": 33393
  },
  {
    "id": "org-6494",
    "slug": "qiziltepa-tumani-18-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 18-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 18 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 18-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "204902633",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Ходжибиби",
    "description": null,
    "isMajor": false,
    "sourceId": 6494
  },
  {
    "id": "org-4478",
    "slug": "qiziltepa-tumani-19-sonli-kamalak-mtt",
    "name": {
      "uz": "Qiziltepa tumani 19-sonli \"Kamalak\" MTT",
      "ru": "Детский сад № 19 «Камалак» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 19-SONLI KAMALAK\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "305523183",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Реватун",
    "description": null,
    "isMajor": false,
    "sourceId": 4478
  },
  {
    "id": "org-14051",
    "slug": "qiziltepa-tumani-19-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 19-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 19 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 19-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "205006852",
    "sectorId": "talim",
    "mahallaId": "xusbuddin",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Хусбудин",
    "description": null,
    "isMajor": true,
    "sourceId": 14051
  },
  {
    "id": "org-33355",
    "slug": "qiziltepa-tumani-2-sonli-quyoshcha-mtt",
    "name": {
      "uz": "Qiziltepa tumani 2-sonli \"Quyoshcha\" MTT",
      "ru": "Детский сад № 2 «Куёшча» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN 2-SONLI QUYOSHCHA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086286",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепа, улица Эзгулик, 17/1",
    "description": null,
    "isMajor": false,
    "sourceId": 33355
  },
  {
    "id": "org-15837",
    "slug": "qiziltepa-tumani-2-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 2-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 2 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 2-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206908820",
    "sectorId": "talim",
    "mahallaId": "gulbog",
    "address": "Gulbogʻ mahallasi Olmazor q/q",
    "description": null,
    "isMajor": false,
    "sourceId": 15837
  },
  {
    "id": "org-875",
    "slug": "qiziltepa-tumani-20-sonli-shodlik-mtt",
    "name": {
      "uz": "Qiziltepa tumani 20-sonli \"Shodlik\" MTT",
      "ru": "Детский сад № 20 «Шодлик» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 20-SONLI SHODLIK\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "305523279",
    "sectorId": "talim",
    "mahallaId": "varozun",
    "address": "VAROZUN MFY",
    "description": null,
    "isMajor": false,
    "sourceId": 875
  },
  {
    "id": "org-2380",
    "slug": "qiziltepa-tumani-21-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 21-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 21 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 21-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "203340908",
    "sectorId": "talim",
    "mahallaId": "kulolon",
    "address": "Kulolom MFY",
    "description": null,
    "isMajor": false,
    "sourceId": 2380
  },
  {
    "id": "org-12609",
    "slug": "qiziltepa-tumani-22-sonli-bolajon-mtt",
    "name": {
      "uz": "Qiziltepa tumani 22-sonli \"Bolajon\" MTT",
      "ru": "Детский сад № 22 «Болажон» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 22-SONLI BOLAJON\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "305696981",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район, городской посёлок",
    "description": null,
    "isMajor": false,
    "sourceId": 12609
  },
  {
    "id": "org-16258",
    "slug": "qiziltepa-tumani-22-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 22-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 22 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 22-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206895104",
    "sectorId": "talim",
    "mahallaId": "oboddiyor",
    "address": "Oboddiyor mfy, Navqiron koʻcha 76-uy",
    "description": null,
    "isMajor": false,
    "sourceId": 16258
  },
  {
    "id": "org-15683",
    "slug": "qiziltepa-tumani-23-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 23-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 23 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 23-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "205006765",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Ташкентская область, Паркентский район, махаллинский сход граждан Обод",
    "description": null,
    "isMajor": false,
    "sourceId": 15683
  },
  {
    "id": "org-15574",
    "slug": "qiziltepa-tumani-25-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 25-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 25 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 25-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "205006813",
    "sectorId": "talim",
    "mahallaId": "qalayi-azizon",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Калъайи Азизон",
    "description": null,
    "isMajor": false,
    "sourceId": 15574
  },
  {
    "id": "org-18587",
    "slug": "qiziltepa-tumani-27-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 27-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 27 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 27-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "203340923",
    "sectorId": "talim",
    "mahallaId": "ortaqorgon",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Уртакурган",
    "description": null,
    "isMajor": true,
    "sourceId": 18587
  },
  {
    "id": "org-6346",
    "slug": "qiziltepa-tumani-28-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 28-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 28 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 28-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "205012403",
    "sectorId": "talim",
    "mahallaId": "ortaqorgon",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Уртакурган",
    "description": null,
    "isMajor": false,
    "sourceId": 6346
  },
  {
    "id": "org-5940",
    "slug": "qiziltepa-tumani-3-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 3-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 3 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 3-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "203181457",
    "sectorId": "talim",
    "mahallaId": "sufiyon",
    "address": "Qiziltepa tuman Soʻfiyon mfy",
    "description": null,
    "isMajor": false,
    "sourceId": 5940
  },
  {
    "id": "org-8496",
    "slug": "qiziltepa-tumani-30-sonli-marjona-mtt",
    "name": {
      "uz": "Qiziltepa tumani 30-sonli \"Marjona\" MTT",
      "ru": "Детский сад № 30 «Маржона» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA   TUMAN     30-SONLI       MARJONA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "306113241",
    "sectorId": "talim",
    "mahallaId": "okmachit",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Окмачит",
    "description": null,
    "isMajor": false,
    "sourceId": 8496
  },
  {
    "id": "org-15449",
    "slug": "qiziltepa-tumani-32-sonli-boston-mtt",
    "name": {
      "uz": "Qiziltepa tumani 32-sonli \"Boʻston\" MTT",
      "ru": "Детский сад № 32 «Бустон» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  32-SONLI     BO`STON\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "306938512",
    "sectorId": "xizmatlar",
    "mahallaId": "goyibon",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Гойибон",
    "description": null,
    "isMajor": false,
    "sourceId": 15449
  },
  {
    "id": "org-39685",
    "slug": "qiziltepa-tumani-34-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 34-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 34 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 34-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206905532",
    "sectorId": "talim",
    "mahallaId": "yangi-hayot-qfy",
    "address": "Навоийская область, Кызылтепинский район, махаллинский сход граждан Янгихаёт",
    "description": null,
    "isMajor": false,
    "sourceId": 39685
  },
  {
    "id": "org-15546",
    "slug": "qiziltepa-tumani-35-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 35-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 35 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 35-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206905524",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Хасанча",
    "description": null,
    "isMajor": false,
    "sourceId": 15546
  },
  {
    "id": "org-1960",
    "slug": "qiziltepa-tumani-36-sonli-mtt",
    "name": {
      "uz": "Qiziltepa tumani 36-sonli MTT",
      "ru": "Детский сад № 36 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 36-SON\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "307990189",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан",
    "description": null,
    "isMajor": false,
    "sourceId": 1960
  },
  {
    "id": "org-15134",
    "slug": "qiziltepa-tumani-38-sonli-davlat-maktabgacha-talim-tashkiloti",
    "name": {
      "uz": "Qiziltepa tumani 38-sonli davlat maktabgacha taʼlim tashkiloti",
      "ru": "Государственная дошкольная образовательная организация № 38 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 38-SONLI DAVLAT MAKTABGACHA TALIM TASHKILOTI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "311159261",
    "sectorId": "talim",
    "mahallaId": "malikobod",
    "address": "Qiziltepa tuman Malikobod mfy",
    "description": null,
    "isMajor": false,
    "sourceId": 15134
  },
  {
    "id": "org-14289",
    "slug": "qiziltepa-tumani-38-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 38-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 38 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 38-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "204471830",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Navoiy shahar Qiziltepa tuman",
    "description": null,
    "isMajor": false,
    "sourceId": 14289
  },
  {
    "id": "org-11373",
    "slug": "qiziltepa-tumani-39-sonli-davlat-maktabgacha-talim-tashkiloti",
    "name": {
      "uz": "Qiziltepa tumani 39-sonli davlat maktabgacha taʼlim tashkiloti",
      "ru": "Государственная дошкольная образовательная организация № 39 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 39-SONLI DAVLAT MAKTABGACHA TA’LIM TASHKILOTI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "311548600",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Узбекистанская ул., 14, Навои",
    "description": null,
    "isMajor": false,
    "sourceId": 11373
  },
  {
    "id": "org-18268",
    "slug": "qiziltepa-tumani-4-sonli-feruza-mtt",
    "name": {
      "uz": "Qiziltepa tumani 4-sonli \"Feruza\" MTT",
      "ru": "Детский сад № 4 «Феруза» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  4-SONLI  FERUZA\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086230",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Махоки",
    "description": null,
    "isMajor": false,
    "sourceId": 18268
  },
  {
    "id": "org-15948",
    "slug": "qiziltepa-tumani-41-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 41-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 41 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 41-SONLI UMUMIY O`RTA TA`LIM\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "306648485",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "qiziltepa 41-maktab",
    "description": null,
    "isMajor": false,
    "sourceId": 15948
  },
  {
    "id": "org-15758",
    "slug": "qiziltepa-tumani-42-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 42-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 42 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMAN 42-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "306646267",
    "sectorId": "talim",
    "mahallaId": "azizobod",
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Азизабад",
    "description": null,
    "isMajor": false,
    "sourceId": 15758
  },
  {
    "id": "org-4445",
    "slug": "qiziltepa-tumani-5-sonli-turnacha-mtt",
    "name": {
      "uz": "Qiziltepa tumani 5-sonli \"Turnacha\" MTT",
      "ru": "Детский сад № 5 «Турнача» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 5-SONLI TURNACHA MAKTABGACHA TA`LIM MUASSASASI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086302",
    "sectorId": "talim",
    "mahallaId": "alisher-navoiy",
    "address": "Qiziltepa tuman A.Navoiy MFY Bahor koʻcha",
    "description": null,
    "isMajor": false,
    "sourceId": 4445
  },
  {
    "id": "org-6426",
    "slug": "qiziltepa-tumani-6-umumiy-orta-talim-maktabi",
    "name": {
      "uz": "Qiziltepa tumani 6-umumiy oʻrta taʼlim maktabi",
      "ru": "Общеобразовательная школа № 6 Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI 6-UMUMIY O`RTA TA`LIM MAKTABI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "school",
    "tin": "206895049",
    "sectorId": "talim",
    "mahallaId": "vangozi",
    "address": "Навоийская область, Кызылтепинский район, городской посёлок Вангози",
    "description": null,
    "isMajor": false,
    "sourceId": 6426
  },
  {
    "id": "org-14274",
    "slug": "qiziltepa-tumani-8-sonli-boychechak-mtt",
    "name": {
      "uz": "Qiziltepa tumani 8-sonli \"Boychechak\" MTT",
      "ru": "Детский сад № 8 «Бойчечак» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  8-SONLI  BOYCHECHAK \" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207028261",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Mirzo Ulugʻbek 79-uy",
    "description": null,
    "isMajor": false,
    "sourceId": 14274
  },
  {
    "id": "org-32263",
    "slug": "qiziltepa-tumani-9-sonli-nilufar-mtt",
    "name": {
      "uz": "Qiziltepa tumani 9-sonli \"Nilufar\" MTT",
      "ru": "Детский сад № 9 «Нилуфар» Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA  TUMAN  9-SONLI  NILUFAR\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "kindergarten",
    "tin": "207086279",
    "sectorId": "talim",
    "mahallaId": "kusharta",
    "address": "Qiziltepa tuman  Xusharti MFY",
    "description": null,
    "isMajor": false,
    "sourceId": 32263
  },
  {
    "id": "org-19443",
    "slug": "qiziltepa-tumani-suv-yetkazib-berish-xizmati",
    "name": {
      "uz": "Qiziltepa tumani suv yetkazib berish xizmati",
      "ru": "Служба водоснабжения Кызылтепинского района"
    },
    "legalName": "\"QIZILTEPA TUMANI SUV YETKAZIB BERISH XIZMATI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "311114777",
    "sectorId": "xizmatlar",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепа, улица Абдулла Кодирий, 39A",
    "description": null,
    "isMajor": false,
    "sourceId": 19443
  },
  {
    "id": "org-12454",
    "slug": "qurilish-taminotchi",
    "name": {
      "uz": "Qurilish taʼminotchi",
      "ru": "ООО «Курилиш таъминотчи»"
    },
    "legalName": "\"КУРИЛИШ ТАЪМИНОТЧИ\"МАЪСУЛЯТИ ЧЕКЛАНГАН ЖАМИЯТИ",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "203512644",
    "sectorId": "qurilish",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район",
    "description": null,
    "isMajor": true,
    "sourceId": 12454
  },
  {
    "id": "org-5937",
    "slug": "svs-navoiy",
    "name": {
      "uz": "SVS Navoiy",
      "ru": "ООО «SVS Navoiy» (иностранное предприятие)"
    },
    "legalName": "\"SVS NAVOIY\" MAS'ULIYATI CHEKLANGAN JAMIYAT XORIJIY KORXONA",
    "legalForm": "MChJ XK",
    "type": "llc",
    "tin": "308508658",
    "sectorId": "sanoat",
    "mahallaId": null,
    "address": "D189",
    "description": null,
    "isMajor": true,
    "sourceId": 5937
  },
  {
    "id": "org-33675",
    "slug": "sanitariya-epidemiologik-osoyishtalik-va-jamoat-salomatligi-qomitasining-qiziltepa-tuman-bolimi",
    "name": {
      "uz": "Sanitariya-epidemiologik osoyishtalik va jamoat salomatligi qoʻmitasining Qiziltepa tuman boʻlimi",
      "ru": "Кызылтепинский районный отдел Комитета санитарно-эпидемиологического благополучия и общественного здоровья"
    },
    "legalName": "\"O'ZBEKISTON RESPUBLIKASI SOG'LIQNI SAQLASH VAZIRLIGI HUZURIDAGI SANITARIYA-EPIDEMIOLOGIK OSOYISHTALIK VA JAMOAT SALOMATLIGI QO'MITASINING NAVOIY VILOYATI BOSHQARMASI QIZILTEPA TUMAN BO'LIMI\" DAVLAT MUASSASASI",
    "legalForm": "DM",
    "type": "state",
    "tin": "200017146",
    "sectorId": "xizmatlar",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": false,
    "sourceId": 33675
  },
  {
    "id": "org-34330",
    "slug": "shifo",
    "name": {
      "uz": "Shifo",
      "ru": "ООО «Shifo»"
    },
    "legalName": "\"SHIFO\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "203256489",
    "sectorId": "sogliqni-saqlash",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": false,
    "sourceId": 34330
  },
  {
    "id": "org-41210",
    "slug": "temur-malik-stroy-grand",
    "name": {
      "uz": "Temur-Malik Stroy Grand",
      "ru": "ООО «Temur-Malik Stroy Grand»"
    },
    "legalName": "\"TEMUR-MALIK STROY GRAND\" MAS`ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "307013698",
    "sectorId": "moliya",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": true,
    "sourceId": 41210
  },
  {
    "id": "org-28395",
    "slug": "toshrabot-bunyodkor-servis",
    "name": {
      "uz": "Toshrabot Bunyodkor Servis",
      "ru": "ООО «Toshrabot Bunyodkor Servis»"
    },
    "legalName": "\"TOSHRABOT BUNYODKOR SERVIS \" MAS'ULIYATI CHEKLANGAN JAMIYAT QO`SHMA KORXONA",
    "legalForm": "MChJ QK",
    "type": "llc",
    "tin": "301025204",
    "sectorId": "sanoat",
    "mahallaId": "malikobod",
    "address": "Навоийская область, Кызылтепинский район, махаллинский сход граждан Маликобод",
    "description": null,
    "isMajor": false,
    "sourceId": 28395
  },
  {
    "id": "org-13370",
    "slug": "uchquduq-barchinoy-gold-777",
    "name": {
      "uz": "Uchquduq Barchinoy Gold 777",
      "ru": "ООО «Uchquduq Barchinoy Gold 777»"
    },
    "legalName": "\"UCHQUDUQ BARCHINOY GOLD 777\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "309744475",
    "sectorId": "sanoat",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район",
    "description": null,
    "isMajor": false,
    "sourceId": 13370
  },
  {
    "id": "org-9170",
    "slug": "vella-plyus",
    "name": {
      "uz": "Vella-Plyus",
      "ru": "ООО «Vella-Plyus»"
    },
    "legalName": "\"VELLA-PLYUS\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "301132855",
    "sectorId": "qurilish",
    "mahallaId": "gulzor",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Гулзор",
    "description": null,
    "isMajor": true,
    "sourceId": 9170
  },
  {
    "id": "org-31350",
    "slug": "yarash-ota-chorvasi",
    "name": {
      "uz": "Yarash Ota Chorvasi",
      "ru": "ООО «Yarash Ota Chorvasi»"
    },
    "legalName": "\"YARASH OTA CHORVASI\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "307212481",
    "sectorId": "sanoat",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": false,
    "sourceId": 31350
  },
  {
    "id": "org-16274",
    "slug": "zafar-azizbek-orzusi",
    "name": {
      "uz": "Zafar Azizbek Orzusi",
      "ru": "ООО «Zafar Azizbek Orzusi»"
    },
    "legalName": "\"ZAFAR    AZIZBEK   ORZUSI\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "307445889",
    "sectorId": "xizmatlar",
    "mahallaId": "kusharta",
    "address": "Навоийская область, Кызылтепинский район, населённый пункт Кушарти",
    "description": null,
    "isMajor": false,
    "sourceId": 16274
  },
  {
    "id": "org-40302",
    "slug": "zamin-agro-oil",
    "name": {
      "uz": "Zamin-Agro Oil",
      "ru": "ООО «Zamin-Agro Oil»"
    },
    "legalName": "\"ZAMIN-AGRO OIL\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "305833803",
    "sectorId": "xizmatlar",
    "mahallaId": "ozbekiston",
    "address": "Навоийская область, Кызылтепа, махаллинский сход граждан Узбекистан, улица Узбекистон",
    "description": null,
    "isMajor": false,
    "sourceId": 40302
  },
  {
    "id": "org-12447",
    "slug": "zarbdor-agro-house",
    "name": {
      "uz": "Zarbdor Agro-House",
      "ru": "ООО «Zarbdor Agro-House»"
    },
    "legalName": "\"ZARBDOR AGRO-HOUSE\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "310229776",
    "sectorId": "qurilish",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепинский район",
    "description": null,
    "isMajor": true,
    "sourceId": 12447
  },
  {
    "id": "org-28486",
    "slug": "zarina-dilara-omadi",
    "name": {
      "uz": "Zarina Dilara Omadi",
      "ru": "Частное предприятие «Zarina Dilara Omadi»"
    },
    "legalName": "\"ZARINA DILARA OMADI\" XUSUSIY KORXONA",
    "legalForm": "XK",
    "type": "private",
    "tin": "308390752",
    "sectorId": "xizmatlar",
    "mahallaId": null,
    "address": "Qiziltepa tumani",
    "description": null,
    "isMajor": false,
    "sourceId": 28486
  },
  {
    "id": "org-31130",
    "slug": "zarmitan-sof-sut",
    "name": {
      "uz": "Zarmitan Sof Sut",
      "ru": "ООО «Zarmitan Sof Sut»"
    },
    "legalName": "\"ZARMITAN SOF SUT\" MAS'ULIYATI CHEKLANGAN JAMIYAT",
    "legalForm": "MChJ",
    "type": "llc",
    "tin": "312093109",
    "sectorId": "xizmatlar",
    "mahallaId": null,
    "address": "D198",
    "description": null,
    "isMajor": false,
    "sourceId": 31130
  },
  {
    "id": "org-32992",
    "slug": "ziyokor-new-school",
    "name": {
      "uz": "Ziyokor New School",
      "ru": "Негосударственное образовательное учреждение «Ziyokor New School»"
    },
    "legalName": "\"ZIYOKOR NEW SCHOOL\" NODAVLAT TA'LIM MUASSASASI",
    "legalForm": "NTM",
    "type": "school",
    "tin": "311648247",
    "sectorId": "talim",
    "mahallaId": null,
    "address": "Навоийская область, Кызылтепа, улица Мирзо Улугбек, 29",
    "description": null,
    "isMajor": false,
    "sourceId": 32992
  }
];
